// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package persistence

import (
	"database/sql"
)

type Issue struct {
	ID           int64
	Link         string
	Title        sql.NullString
	Description  sql.NullString
	Owner        sql.NullString
	CreationDate sql.NullTime
}
