// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package persistence

import (
	"database/sql"
	"time"
)

type Issue struct {
	Url           string
	RepoWithOwner string
	Title         string
	Description   string
	CreationDate  time.Time
}

type Repo struct {
	RepoWithOwner   string
	Description     sql.NullString
	StargazersCount sql.NullInt64
	Language        sql.NullString
}

type TaskDatum struct {
	ID         int64
	LastRun    sql.NullTime
	InProgress sql.NullBool
}
